version: '3.1'

services:
  svc-sonarqube-database:
    image: postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=sonarqube
      - POSTGRES_USER=sonarqubedbadmin
      - POSTGRES_PASSWORD=ExtraStores777
    volumes:
      - vol-sonarqube-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - net-sonarqube
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - '5432:5432'

  svc-sonarqube-app:
    image: sonarqube
    ports:
      - '9000:9000'
      - '9092:9092'
      
    networks:
      - net-sonarqube
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqubedbadmin
      - SONARQUBE_JDBC_PASSWORD=ExtraStores777
      - SONARQUBE_JDBC_URL=jdbc:postgresql://svc-sonarqube-database:5432/sonarqube

    volumes:
      - 'vol-sonarqube-app-conf:/opt/sonarqube/conf'
      - 'vol-sonarqube-app-data:/opt/sonarqube/data'
      - 'vol-sonarqube-app-extensions:/opt/sonarqube/extensions'
      - 'vol-sonarqube-app-plugins:/opt/sonarqube/lib/bundled-plugins'
    depends_on:
      - svc-sonarqube-database
    deploy:
      replicas: 1
      
volumes:
  vol-sonarqube-db-data:
    driver: rexray/azureud
    driver_opts:
      share: vol-sonarqube-db-data
      gid: 1001
      uid: 1001
      perfmode: maxio      
      filemode: 0777
      dirmode: 0777
      size: 50  

  vol-sonarqube-app-conf:
    driver: cloudstor:azure
    driver_opts:
      share: vol-sonarqube-app-conf
      gid: 1001
      uid: 1001
      perfmode: maxio      
      filemode: 0777
      dirmode: 0777
      size: 1  

  vol-sonarqube-app-data:
    driver: cloudstor:azure
    driver_opts:
      share: vol-sonarqube-app-data
      gid: 1001
      uid: 1001
      perfmode: maxio      
      filemode: 0777
      dirmode: 0777
      size: 10  

  vol-sonarqube-app-extensions:
    driver: cloudstor:azure
    driver_opts:
      share: vol-sonarqube-app-extensions
      gid: 1001
      uid: 1001
      perfmode: maxio      
      filemode: 0777
      dirmode: 0777
      size: 5  

  vol-sonarqube-app-plugins:
    driver: cloudstor:azure
    driver_opts:
      share: vol-sonarqube-app-plugins
      gid: 1001
      uid: 1001
      perfmode: maxio      
      filemode: 0777
      dirmode: 0777
      size: 5  
      
networks:
  net-sonarqube:
    driver: overlay

