version: '3.1'

services:
  sonarqube-database:
    image: postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=sonarqube
      - POSTGRES_USER=sonarqubedbadmin
      - POSTGRES_PASSWORD=ExtraStores777
    volumes:
      - sonarqube-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - sonarqube-net
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - '5432:5432'

  sonarqube-app:
    image: sonarqube
    ports:
      - '9000:9000'
      - '9092:9092'
      
    networks:
      - sonarqube-net
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqubedbadmin
      - SONARQUBE_JDBC_PASSWORD=ExtraStores777   
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-database:5432/sonarqube

    volumes:
      - 'sonarqube-app-conf:/opt/sonarqube/conf'
      - 'sonarqube-app-data:/opt/sonarqube/data'
      - 'sonarqube-app-extensions:/opt/sonarqube/extensions'
      - 'sonarqube-app-plugins:/opt/sonarqube/lib/bundled-plugins'
    depends_on:
      - sonarqube-database
    deploy:
      replicas: 1
 
volumes:
  sonarqube-db-data:
    driver: rexray/azureud
    driver_opts:
      share: sonarqube-db-data
      gid: 1001
      uid: 1001
      perfmode: maxio      
      filemode: 0777
      dirmode: 0777
      size: 50  

  sonarqube-app-conf:
    driver: cloudstor:azure
    driver_opts:
      share: sonarqube-app-conf
      gid: 1001
      uid: 1001
      perfmode: maxio      
      filemode: 0777
      dirmode: 0777
      size: 5 

  sonarqube-app-data:
    driver: cloudstor:azure
    driver_opts:
      share: sonarqube-app-data
      gid: 1001
      uid: 1001
      perfmode: maxio      
      filemode: 0777
      dirmode: 0777
      size: 2  

  sonarqube-app-extensions:
    driver: cloudstor:azure
    driver_opts:
      share: sonarqube-app-extensions
      gid: 1001
      uid: 1001
      perfmode: maxio      
      filemode: 0777
      dirmode: 0777
      size: 1  

  sonarqube-app-plugins:
    driver: cloudstor:azure
    driver_opts:
      share: sonarqube-app-plugins
      gid: 1001
      uid: 1001
      perfmode: maxio      
      filemode: 0777
      dirmode: 0777
      size: 1  
            
networks:

  sonarqube-net:
    driver: overlay
    
